//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace AdventureTerreInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using AdventureTerreInterfaces;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class MonsterGrainFactory
    {
        

                        public static AdventureTerreInterfaces.IMonsterGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IMonsterGrain), -1660643888, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IMonsterGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IMonsterGrain), -1660643888, primaryKey, grainClassNamePrefix));
                        }

                        public static AdventureTerreInterfaces.IMonsterGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IMonsterGrain), -1660643888, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IMonsterGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IMonsterGrain), -1660643888, primaryKey, grainClassNamePrefix));
                        }

            public static AdventureTerreInterfaces.IMonsterGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return MonsterGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IMonsterGrain")]
        internal class MonsterGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, AdventureTerreInterfaces.IMonsterGrain
        {
            

            public static AdventureTerreInterfaces.IMonsterGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (AdventureTerreInterfaces.IMonsterGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(AdventureTerreInterfaces.IMonsterGrain), (global::Orleans.Runtime.GrainReference gr) => { return new MonsterGrainReference(gr);}, grainRef, -1660643888);
            }
            
            protected internal MonsterGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal MonsterGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -1660643888;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "AdventureTerreInterfaces.AdventureTerreInterfaces.IMonsterGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                MonsterGrainReference input = ((MonsterGrainReference)(original));
                return ((MonsterGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                MonsterGrainReference input = ((MonsterGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return MonsterGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return MonsterGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<string> AdventureTerreInterfaces.IMonsterGrain.Name()
            {

                return base.InvokeMethodAsync<System.String>(-67873697, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IMonsterGrain.SetInfo(AdventureTerreInterfaces.MonsterInfo info)
            {

                return base.InvokeMethodAsync<object>(1642984836, new object[] {info} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IMonsterGrain.SetPlayerGuid(System.Guid playerGuid)
            {

                return base.InvokeMethodAsync<object>(970082334, new object[] {playerGuid} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IMonsterGrain.SetRoomGrain(AdventureTerreInterfaces.IRoomGrain room)
            {

                return base.InvokeMethodAsync<object>(-1091530947, new object[] {room is global::Orleans.Grain ? AdventureTerreInterfaces.RoomGrainFactory.Cast(room.AsReference()) : room} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.IRoomGrain> AdventureTerreInterfaces.IMonsterGrain.RoomGrain()
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.IRoomGrain>(2108089454, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> AdventureTerreInterfaces.IMonsterGrain.Kill(AdventureTerreInterfaces.IRoomGrain room)
            {

                return base.InvokeMethodAsync<System.String>(122057053, new object[] {room is global::Orleans.Grain ? AdventureTerreInterfaces.RoomGrainFactory.Cast(room.AsReference()) : room} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IMonsterGrain.ClearGrainAndState()
            {

                return base.InvokeMethodAsync<object>(-1370817314, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IMonsterGrain", -1660643888)]
    internal class MonsterGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -1660643888;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1660643888:  // IMonsterGrain
                        switch (methodId)
                        {
                            case -67873697: 
                                return ((IMonsterGrain)grain).Name().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1642984836: 
                                return ((IMonsterGrain)grain).SetInfo((MonsterInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 970082334: 
                                return ((IMonsterGrain)grain).SetPlayerGuid((Guid)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1091530947: 
                                return ((IMonsterGrain)grain).SetRoomGrain((IRoomGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 2108089454: 
                                return ((IMonsterGrain)grain).RoomGrain().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 122057053: 
                                return ((IMonsterGrain)grain).Kill((IRoomGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1370817314: 
                                return ((IMonsterGrain)grain).ClearGrainAndState().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1660643888:  // IMonsterGrain
                    switch (methodId)
                    {
                        case -67873697:
                            return "Name";
                    case 1642984836:
                            return "SetInfo";
                    case 970082334:
                            return "SetPlayerGuid";
                    case -1091530947:
                            return "SetRoomGrain";
                    case 2108089454:
                            return "RoomGrain";
                    case 122057053:
                            return "Kill";
                    case -1370817314:
                            return "ClearGrainAndState";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PlayerGrainFactory
    {
        

                        public static AdventureTerreInterfaces.IPlayerGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPlayerGrain), -942525015, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IPlayerGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPlayerGrain), -942525015, primaryKey, grainClassNamePrefix));
                        }

                        public static AdventureTerreInterfaces.IPlayerGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPlayerGrain), -942525015, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IPlayerGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPlayerGrain), -942525015, primaryKey, grainClassNamePrefix));
                        }

            public static AdventureTerreInterfaces.IPlayerGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return PlayerGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IPlayerGrain")]
        internal class PlayerGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, AdventureTerreInterfaces.IPlayerGrain
        {
            

            public static AdventureTerreInterfaces.IPlayerGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (AdventureTerreInterfaces.IPlayerGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(AdventureTerreInterfaces.IPlayerGrain), (global::Orleans.Runtime.GrainReference gr) => { return new PlayerGrainReference(gr);}, grainRef, -942525015);
            }
            
            protected internal PlayerGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal PlayerGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -942525015;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "AdventureTerreInterfaces.AdventureTerreInterfaces.IPlayerGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                PlayerGrainReference input = ((PlayerGrainReference)(original));
                return ((PlayerGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                PlayerGrainReference input = ((PlayerGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return PlayerGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return PlayerGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<System.Guid> AdventureTerreInterfaces.IPlayerGrain.GetPlayerGuid()
            {

                return base.InvokeMethodAsync<System.Guid>(1000798450, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.ProcessMessage(string message)
            {

                return base.InvokeMethodAsync<object>(165839099, new object[] {message} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.AddRoom(AdventureTerreInterfaces.IRoomGrain room)
            {

                return base.InvokeMethodAsync<object>(2015221033, new object[] {room is global::Orleans.Grain ? AdventureTerreInterfaces.RoomGrainFactory.Cast(room.AsReference()) : room} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.AddMonster(AdventureTerreInterfaces.IMonsterGrain monster)
            {

                return base.InvokeMethodAsync<object>(-87135492, new object[] {monster is global::Orleans.Grain ? AdventureTerreInterfaces.MonsterGrainFactory.Cast(monster.AsReference()) : monster} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.IRoomGrain> AdventureTerreInterfaces.IPlayerGrain.GetRoomGrainByRoomId(long id)
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.IRoomGrain>(-1842518931, new object[] {id} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.IRoomGrain> AdventureTerreInterfaces.IPlayerGrain.GetRandomRoom()
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.IRoomGrain>(266555913, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.SetupRooms()
            {

                return base.InvokeMethodAsync<object>(-1411277920, new object[] {} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.PlayerInfo> AdventureTerreInterfaces.IPlayerGrain.GetPlayerInfo()
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.PlayerInfo>(230104561, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> AdventureTerreInterfaces.IPlayerGrain.Name()
            {

                return base.InvokeMethodAsync<System.String>(-67873697, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.SetName(string name)
            {

                return base.InvokeMethodAsync<object>(316304768, new object[] {name} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.SetInfoGuid(System.Guid guid)
            {

                return base.InvokeMethodAsync<object>(2059873073, new object[] {guid} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.IRoomGrain> AdventureTerreInterfaces.IPlayerGrain.RoomGrain()
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.IRoomGrain>(2108089454, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.Die()
            {

                return base.InvokeMethodAsync<object>(-1632993044, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> AdventureTerreInterfaces.IPlayerGrain.Play(string command)
            {

                return base.InvokeMethodAsync<System.String>(646042025, new object[] {command} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPlayerGrain.ClearGrainAndState()
            {

                return base.InvokeMethodAsync<object>(-1370817314, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IPlayerGrain", -942525015)]
    internal class PlayerGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -942525015;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -942525015:  // IPlayerGrain
                        switch (methodId)
                        {
                            case 1000798450: 
                                return ((IPlayerGrain)grain).GetPlayerGuid().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 165839099: 
                                return ((IPlayerGrain)grain).ProcessMessage((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 2015221033: 
                                return ((IPlayerGrain)grain).AddRoom((IRoomGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -87135492: 
                                return ((IPlayerGrain)grain).AddMonster((IMonsterGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1842518931: 
                                return ((IPlayerGrain)grain).GetRoomGrainByRoomId((Int64)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 266555913: 
                                return ((IPlayerGrain)grain).GetRandomRoom().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1411277920: 
                                return ((IPlayerGrain)grain).SetupRooms().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 230104561: 
                                return ((IPlayerGrain)grain).GetPlayerInfo().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -67873697: 
                                return ((IPlayerGrain)grain).Name().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 316304768: 
                                return ((IPlayerGrain)grain).SetName((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 2059873073: 
                                return ((IPlayerGrain)grain).SetInfoGuid((Guid)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 2108089454: 
                                return ((IPlayerGrain)grain).RoomGrain().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1632993044: 
                                return ((IPlayerGrain)grain).Die().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 646042025: 
                                return ((IPlayerGrain)grain).Play((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1370817314: 
                                return ((IPlayerGrain)grain).ClearGrainAndState().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -942525015:  // IPlayerGrain
                    switch (methodId)
                    {
                        case 1000798450:
                            return "GetPlayerGuid";
                    case 165839099:
                            return "ProcessMessage";
                    case 2015221033:
                            return "AddRoom";
                    case -87135492:
                            return "AddMonster";
                    case -1842518931:
                            return "GetRoomGrainByRoomId";
                    case 266555913:
                            return "GetRandomRoom";
                    case -1411277920:
                            return "SetupRooms";
                    case 230104561:
                            return "GetPlayerInfo";
                    case -67873697:
                            return "Name";
                    case 316304768:
                            return "SetName";
                    case 2059873073:
                            return "SetInfoGuid";
                    case 2108089454:
                            return "RoomGrain";
                    case -1632993044:
                            return "Die";
                    case 646042025:
                            return "Play";
                    case -1370817314:
                            return "ClearGrainAndState";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PushNotifierGrainFactory
    {
        

                        public static AdventureTerreInterfaces.IPushNotifierGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPushNotifierGrain), 1418956188, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IPushNotifierGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPushNotifierGrain), 1418956188, primaryKey, grainClassNamePrefix));
                        }

                        public static AdventureTerreInterfaces.IPushNotifierGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPushNotifierGrain), 1418956188, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IPushNotifierGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IPushNotifierGrain), 1418956188, primaryKey, grainClassNamePrefix));
                        }

            public static AdventureTerreInterfaces.IPushNotifierGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return PushNotifierGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IPushNotifierGrain")]
        internal class PushNotifierGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, AdventureTerreInterfaces.IPushNotifierGrain
        {
            

            public static AdventureTerreInterfaces.IPushNotifierGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (AdventureTerreInterfaces.IPushNotifierGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(AdventureTerreInterfaces.IPushNotifierGrain), (global::Orleans.Runtime.GrainReference gr) => { return new PushNotifierGrainReference(gr);}, grainRef, 1418956188);
            }
            
            protected internal PushNotifierGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal PushNotifierGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1418956188;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "AdventureTerreInterfaces.AdventureTerreInterfaces.IPushNotifierGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                PushNotifierGrainReference input = ((PushNotifierGrainReference)(original));
                return ((PushNotifierGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                PushNotifierGrainReference input = ((PushNotifierGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return PushNotifierGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return PushNotifierGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPushNotifierGrain.SendMessage(string message)
            {

                return base.InvokeMethodAsync<object>(1983731744, new object[] {message} , options:  global::Orleans.CodeGeneration.InvokeMethodOptions.Unordered);
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPushNotifierGrain.SendMessage(string message, string recipient)
            {

                return base.InvokeMethodAsync<object>(-419561747, new object[] {message, recipient} , options:  global::Orleans.CodeGeneration.InvokeMethodOptions.Unordered);
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IPushNotifierGrain.ClearGrainAndState()
            {

                return base.InvokeMethodAsync<object>(-1370817314, new object[] {} , options:  global::Orleans.CodeGeneration.InvokeMethodOptions.Unordered);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IPushNotifierGrain", 1418956188)]
    internal class PushNotifierGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1418956188;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1418956188:  // IPushNotifierGrain
                        switch (methodId)
                        {
                            case 1983731744: 
                                return ((IPushNotifierGrain)grain).SendMessage((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -419561747: 
                                return ((IPushNotifierGrain)grain).SendMessage((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1370817314: 
                                return ((IPushNotifierGrain)grain).ClearGrainAndState().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1418956188:  // IPushNotifierGrain
                    switch (methodId)
                    {
                        case 1983731744:
                            return "SendMessage";
                    case -419561747:
                            return "SendMessage";
                    case -1370817314:
                            return "ClearGrainAndState";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class RoomGrainFactory
    {
        

                        public static AdventureTerreInterfaces.IRoomGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IRoomGrain), -1726192713, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IRoomGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IRoomGrain), -1726192713, primaryKey, grainClassNamePrefix));
                        }

                        public static AdventureTerreInterfaces.IRoomGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IRoomGrain), -1726192713, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IRoomGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IRoomGrain), -1726192713, primaryKey, grainClassNamePrefix));
                        }

            public static AdventureTerreInterfaces.IRoomGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return RoomGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IRoomGrain")]
        internal class RoomGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, AdventureTerreInterfaces.IRoomGrain
        {
            

            public static AdventureTerreInterfaces.IRoomGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (AdventureTerreInterfaces.IRoomGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(AdventureTerreInterfaces.IRoomGrain), (global::Orleans.Runtime.GrainReference gr) => { return new RoomGrainReference(gr);}, grainRef, -1726192713);
            }
            
            protected internal RoomGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal RoomGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -1726192713;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "AdventureTerreInterfaces.AdventureTerreInterfaces.IRoomGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                RoomGrainReference input = ((RoomGrainReference)(original));
                return ((RoomGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                RoomGrainReference input = ((RoomGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return RoomGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return RoomGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<string> AdventureTerreInterfaces.IRoomGrain.Description(AdventureTerreInterfaces.PlayerInfo whoisAsking)
            {

                return base.InvokeMethodAsync<System.String>(288293111, new object[] {whoisAsking} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.SetInfo(AdventureTerreInterfaces.RoomInfo info)
            {

                return base.InvokeMethodAsync<object>(-1430615142, new object[] {info} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.IRoomGrain> AdventureTerreInterfaces.IRoomGrain.ExitTo(string direction)
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.IRoomGrain>(-323822931, new object[] {direction} );
            }
            
            System.Threading.Tasks.Task<long> AdventureTerreInterfaces.IRoomGrain.RoomId()
            {

                return base.InvokeMethodAsync<System.Int64>(-1179561461, new object[] {} );
            }
            
            System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, long>> AdventureTerreInterfaces.IRoomGrain.ExitRoomIds()
            {

                return base.InvokeMethodAsync<System.Collections.Generic.Dictionary<System.String,System.Int64>>(2010704602, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.SetExitRoomForKey(string key, AdventureTerreInterfaces.IRoomGrain roomGrain)
            {

                return base.InvokeMethodAsync<object>(2017027896, new object[] {key, roomGrain is global::Orleans.Grain ? AdventureTerreInterfaces.RoomGrainFactory.Cast(roomGrain.AsReference()) : roomGrain} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Enter(AdventureTerreInterfaces.PlayerInfo player)
            {

                return base.InvokeMethodAsync<object>(2139370243, new object[] {player} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Exit(AdventureTerreInterfaces.PlayerInfo player)
            {

                return base.InvokeMethodAsync<object>(1116324557, new object[] {player} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Enter(AdventureTerreInterfaces.MonsterInfo monster)
            {

                return base.InvokeMethodAsync<object>(-1993785949, new object[] {monster} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Exit(AdventureTerreInterfaces.MonsterInfo monster)
            {

                return base.InvokeMethodAsync<object>(-328248759, new object[] {monster} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Drop(AdventureTerreInterfaces.Thing thing)
            {

                return base.InvokeMethodAsync<object>(1453036231, new object[] {thing} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.Take(AdventureTerreInterfaces.Thing thing)
            {

                return base.InvokeMethodAsync<object>(1542534434, new object[] {thing} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.Thing> AdventureTerreInterfaces.IRoomGrain.FindThing(string name)
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.Thing>(-1840220455, new object[] {name} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.PlayerInfo> AdventureTerreInterfaces.IRoomGrain.FindPlayer(string name)
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.PlayerInfo>(22289778, new object[] {name} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.MonsterInfo> AdventureTerreInterfaces.IRoomGrain.FindMonster(string name)
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.MonsterInfo>(-649945656, new object[] {name} );
            }
            
            System.Threading.Tasks.Task<AdventureTerreInterfaces.PlayerInfo[]> AdventureTerreInterfaces.IRoomGrain.GetPlayersInRoom()
            {

                return base.InvokeMethodAsync<AdventureTerreInterfaces.PlayerInfo[]>(1848004524, new object[] {} );
            }
            
            System.Threading.Tasks.Task AdventureTerreInterfaces.IRoomGrain.ClearGrainAndState()
            {

                return base.InvokeMethodAsync<object>(-1370817314, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IRoomGrain", -1726192713)]
    internal class RoomGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -1726192713;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1726192713:  // IRoomGrain
                        switch (methodId)
                        {
                            case 288293111: 
                                return ((IRoomGrain)grain).Description((PlayerInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1430615142: 
                                return ((IRoomGrain)grain).SetInfo((RoomInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -323822931: 
                                return ((IRoomGrain)grain).ExitTo((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1179561461: 
                                return ((IRoomGrain)grain).RoomId().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 2010704602: 
                                return ((IRoomGrain)grain).ExitRoomIds().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 2017027896: 
                                return ((IRoomGrain)grain).SetExitRoomForKey((String)arguments[0], (IRoomGrain)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 2139370243: 
                                return ((IRoomGrain)grain).Enter((PlayerInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1116324557: 
                                return ((IRoomGrain)grain).Exit((PlayerInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1993785949: 
                                return ((IRoomGrain)grain).Enter((MonsterInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -328248759: 
                                return ((IRoomGrain)grain).Exit((MonsterInfo)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1453036231: 
                                return ((IRoomGrain)grain).Drop((Thing)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1542534434: 
                                return ((IRoomGrain)grain).Take((Thing)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1840220455: 
                                return ((IRoomGrain)grain).FindThing((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 22289778: 
                                return ((IRoomGrain)grain).FindPlayer((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -649945656: 
                                return ((IRoomGrain)grain).FindMonster((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1848004524: 
                                return ((IRoomGrain)grain).GetPlayersInRoom().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1370817314: 
                                return ((IRoomGrain)grain).ClearGrainAndState().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1726192713:  // IRoomGrain
                    switch (methodId)
                    {
                        case 288293111:
                            return "Description";
                    case -1430615142:
                            return "SetInfo";
                    case -323822931:
                            return "ExitTo";
                    case -1179561461:
                            return "RoomId";
                    case 2010704602:
                            return "ExitRoomIds";
                    case 2017027896:
                            return "SetExitRoomForKey";
                    case 2139370243:
                            return "Enter";
                    case 1116324557:
                            return "Exit";
                    case -1993785949:
                            return "Enter";
                    case -328248759:
                            return "Exit";
                    case 1453036231:
                            return "Drop";
                    case 1542534434:
                            return "Take";
                    case -1840220455:
                            return "FindThing";
                    case 22289778:
                            return "FindPlayer";
                    case -649945656:
                            return "FindMonster";
                    case 1848004524:
                            return "GetPlayersInRoom";
                    case -1370817314:
                            return "ClearGrainAndState";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class UniverseGrainFactory
    {
        

                        public static AdventureTerreInterfaces.IUniverseGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IUniverseGrain), -446839258, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IUniverseGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IUniverseGrain), -446839258, primaryKey, grainClassNamePrefix));
                        }

                        public static AdventureTerreInterfaces.IUniverseGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IUniverseGrain), -446839258, primaryKey));
                        }

                        public static AdventureTerreInterfaces.IUniverseGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(AdventureTerreInterfaces.IUniverseGrain), -446839258, primaryKey, grainClassNamePrefix));
                        }

            public static AdventureTerreInterfaces.IUniverseGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return UniverseGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IUniverseGrain")]
        internal class UniverseGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, AdventureTerreInterfaces.IUniverseGrain
        {
            

            public static AdventureTerreInterfaces.IUniverseGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (AdventureTerreInterfaces.IUniverseGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(AdventureTerreInterfaces.IUniverseGrain), (global::Orleans.Runtime.GrainReference gr) => { return new UniverseGrainReference(gr);}, grainRef, -446839258);
            }
            
            protected internal UniverseGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal UniverseGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -446839258;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "AdventureTerreInterfaces.AdventureTerreInterfaces.IUniverseGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                UniverseGrainReference input = ((UniverseGrainReference)(original));
                return ((UniverseGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                UniverseGrainReference input = ((UniverseGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return UniverseGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return UniverseGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("AdventureTerreInterfaces.AdventureTerreInterfaces.IUniverseGrain", -446839258)]
    internal class UniverseGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -446839258;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -446839258:  // IUniverseGrain
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -446839258:  // IUniverseGrain
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class AdventureTerreInterfaces_MonsterInfoSerialization
    {
        
        static AdventureTerreInterfaces_MonsterInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            AdventureTerreInterfaces.MonsterInfo input = ((AdventureTerreInterfaces.MonsterInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Int64));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Key, stream, typeof(Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.KilledBy, stream, typeof(List<Int64>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            AdventureTerreInterfaces.MonsterInfo result = new AdventureTerreInterfaces.MonsterInfo();
            result.Id = ((Int64)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int64), stream)));
            result.Key = ((Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Guid), stream)));
            result.KilledBy = ((List<Int64>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<Int64>), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(AdventureTerreInterfaces.MonsterInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class AdventureTerreInterfaces_PlayerInfoSerialization
    {
        
        static AdventureTerreInterfaces_PlayerInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            AdventureTerreInterfaces.PlayerInfo input = ((AdventureTerreInterfaces.PlayerInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Key, stream, typeof(Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            AdventureTerreInterfaces.PlayerInfo result = new AdventureTerreInterfaces.PlayerInfo();
            result.Key = ((Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Guid), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(AdventureTerreInterfaces.PlayerInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class AdventureTerreInterfaces_RoomInfoSerialization
    {
        
        static AdventureTerreInterfaces_RoomInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            AdventureTerreInterfaces.RoomInfo input = ((AdventureTerreInterfaces.RoomInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Description, stream, typeof(String));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Directions, stream, typeof(Dictionary<String,Int64>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Int64));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            AdventureTerreInterfaces.RoomInfo result = new AdventureTerreInterfaces.RoomInfo();
            result.Description = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            result.Directions = ((Dictionary<String,Int64>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dictionary<String,Int64>), stream)));
            result.Id = ((Int64)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int64), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(AdventureTerreInterfaces.RoomInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class AdventureTerreInterfaces_ThingSerialization
    {
        
        static AdventureTerreInterfaces_ThingSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            AdventureTerreInterfaces.Thing input = ((AdventureTerreInterfaces.Thing)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Category, stream, typeof(String));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Commands, stream, typeof(List<String>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.FoundIn, stream, typeof(Int64));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Int64));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            AdventureTerreInterfaces.Thing result = new AdventureTerreInterfaces.Thing();
            result.Category = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            result.Commands = ((List<String>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<String>), stream)));
            result.FoundIn = ((Int64)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int64), stream)));
            result.Id = ((Int64)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int64), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(AdventureTerreInterfaces.Thing), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
