//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace AdventureTerreGrains
{
    using AdventureTerreInterfaces;
    using Orleans;
    using Orleans.Runtime;
    using System;
    using Orleans.CodeGeneration;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("AdventureTerreGrains.AdventureTerreGrains.MonsterGrain")]
    public class MonsterGrainState : global::Orleans.CodeGeneration.GrainState, IMonsterState
    {
        

            public MonsterInfo monsterInfo { get; set; }

            public IRoomGrain roomGrain { get; set; }

            public Guid playerGuid { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("monsterInfo", out value)) monsterInfo = (MonsterInfo) value;
                if (values.TryGetValue("roomGrain", out value)) roomGrain = (IRoomGrain) value;
                if (values.TryGetValue("playerGuid", out value)) playerGuid = (Guid) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("MonsterGrainState( monsterInfo={0} roomGrain={1} playerGuid={2} )", monsterInfo, roomGrain, playerGuid);
            }
        
        public MonsterGrainState() : 
                base("AdventureTerreGrains.MonsterGrain")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["monsterInfo"] = this.monsterInfo;
            result["roomGrain"] = this.roomGrain;
            result["playerGuid"] = this.playerGuid;
            return result;
        }
        
        private void InitStateFields()
        {
            this.monsterInfo = new MonsterInfo();
            this.roomGrain = default(IRoomGrain);
            this.playerGuid = default(Guid);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            MonsterGrainState input = ((MonsterGrainState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            MonsterGrainState input = ((MonsterGrainState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            MonsterGrainState result = new MonsterGrainState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("AdventureTerreGrains.AdventureTerreGrains.PlayerGrain")]
    public class PlayerGrainState : global::Orleans.CodeGeneration.GrainState, IPlayerState
    {
        

            public IRoomGrain roomGrain { get; set; }

            public List<Thing> things { get; set; }

            public List<IRoomGrain> roomGrains { get; set; }

            public List<IMonsterGrain> monsterGrains { get; set; }

            public Boolean killed { get; set; }

            public PlayerInfo myInfo { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("roomGrain", out value)) roomGrain = (IRoomGrain) value;
                if (values.TryGetValue("things", out value)) things = (List<Thing>) value;
                if (values.TryGetValue("roomGrains", out value)) roomGrains = (List<IRoomGrain>) value;
                if (values.TryGetValue("monsterGrains", out value)) monsterGrains = (List<IMonsterGrain>) value;
                if (values.TryGetValue("killed", out value)) killed = (Boolean) value;
                if (values.TryGetValue("myInfo", out value)) myInfo = (PlayerInfo) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("PlayerGrainState( roomGrain={0} things={1} roomGrains={2} monsterGrains={3} killed={4} myInfo={5} )", roomGrain, things, roomGrains, monsterGrains, killed, myInfo);
            }
        
        public PlayerGrainState() : 
                base("AdventureTerreGrains.PlayerGrain")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["roomGrain"] = this.roomGrain;
            result["things"] = this.things;
            result["roomGrains"] = this.roomGrains;
            result["monsterGrains"] = this.monsterGrains;
            result["killed"] = this.killed;
            result["myInfo"] = this.myInfo;
            return result;
        }
        
        private void InitStateFields()
        {
            this.roomGrain = default(IRoomGrain);
            this.things = new List<Thing>();
            this.roomGrains = new List<IRoomGrain>();
            this.monsterGrains = new List<IMonsterGrain>();
            this.killed = default(Boolean);
            this.myInfo = new PlayerInfo();
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            PlayerGrainState input = ((PlayerGrainState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            PlayerGrainState input = ((PlayerGrainState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            PlayerGrainState result = new PlayerGrainState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("AdventureTerreGrains.AdventureTerreGrains.RoomGrain")]
    public class RoomGrainState : global::Orleans.CodeGeneration.GrainState, IRoomState
    {
        

            public String description { get; set; }

            public Int64 roomId { get; set; }

            public List<PlayerInfo> players { get; set; }

            public List<MonsterInfo> monsters { get; set; }

            public List<Thing> things { get; set; }

            public Dictionary<String,IRoomGrain> exits { get; set; }

            public Dictionary<String,Int64> exitRoomIds { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("description", out value)) description = (String) value;
                if (values.TryGetValue("roomId", out value)) roomId = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("players", out value)) players = (List<PlayerInfo>) value;
                if (values.TryGetValue("monsters", out value)) monsters = (List<MonsterInfo>) value;
                if (values.TryGetValue("things", out value)) things = (List<Thing>) value;
                if (values.TryGetValue("exits", out value)) exits = (Dictionary<String,IRoomGrain>) value;
                if (values.TryGetValue("exitRoomIds", out value)) exitRoomIds = (Dictionary<String,Int64>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("RoomGrainState( description={0} roomId={1} players={2} monsters={3} things={4} exits={5} exitRoomIds={6} )", description, roomId, players, monsters, things, exits, exitRoomIds);
            }
        
        public RoomGrainState() : 
                base("AdventureTerreGrains.RoomGrain")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["description"] = this.description;
            result["roomId"] = this.roomId;
            result["players"] = this.players;
            result["monsters"] = this.monsters;
            result["things"] = this.things;
            result["exits"] = this.exits;
            result["exitRoomIds"] = this.exitRoomIds;
            return result;
        }
        
        private void InitStateFields()
        {
            this.description = default(String);
            this.roomId = default(Int64);
            this.players = new List<PlayerInfo>();
            this.monsters = new List<MonsterInfo>();
            this.things = new List<Thing>();
            this.exits = new Dictionary<String,IRoomGrain>();
            this.exitRoomIds = new Dictionary<String,Int64>();
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            RoomGrainState input = ((RoomGrainState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            RoomGrainState input = ((RoomGrainState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            RoomGrainState result = new RoomGrainState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
